# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/
baseURL = "https://jamesjarvis.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 10
colorScheme = "ocean"

timeout = '3000s'

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
posts = '/posts/:year/:month/:title/'

[pagination]
path = 'page'
pagerSize = '20'

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = false
privacyEnhanced = true

[imaging]
quality = 75
disableDate = true

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      inline = true
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.svg]
      inline = true
