name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: install
        run: yarn install

      - name: build staging
        if: github.ref != 'refs/heads/master'
        run: GATSBY_ACTIVE_ENV=staging yarn build

      - name: build prod
        if: github.ref == 'refs/heads/master'
        run: yarn build

      - name: Run Lighthouse analysis
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: jamesjarvis.io
