name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.114.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload built state
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download compiled site
        uses: actions/download-artifact@v1
        with:
          name: site
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: jamesjarvis.io
          force_orphan: true

  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download compiled site
        uses: actions/download-artifact@v1
        with:
          name: site
          path: public
      - name: Run Lighthouse analysis
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 1
